use_frameworks!

platform :ios, '8.0'

target 'LffHealper_Example' do
  pod 'LffHealper', :path => '../'

  target 'LffHealper_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
